name:    ${project.artifactId}
main:    ${project.groupId}.${project.artifactId}.BukkitPluginMain
version: ${project.version}
website: ${project.url}
author:  SimSonic
commands:
  rscm:
    description: ${project.artifactId} command hub
    usage: /<command> do what?
permissions:
  rscm.admin:
    description: Access to all functions
    default: op
